package co.wethinkcode.logisticsconnect;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class IngestionServiceAppTest {

    // Create a single, reusable HTTP client that acts as a web browser
    // Same HTTP client shared amongst our tests
    private static final HttpClient client = HttpClient.newHttpClient();
    
    @BeforeAll
    public static void setup() throws InterruptedException {
        // Start Javalin app in a background thread on port 7050
        // If we didn't put it in a background thread, the program would pause here forever and tests would never run.
        new Thread(() -> IngestionServiceApp.main(new String[0])).start();

        // Provide a 3second buffer for the sever to parse the CSV and bind to the port
        Thread.sleep(3000);
    }

    @Test
    public void testHealthEndpoint() throws Exception {
        // Build an HTTP GET request aimed at our local health check URL
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:7050/health"))
                .GET()
                .build();
        // Send the request using our client and wait for the response as a standard String
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

        // Assert that the HTTP Status Code we received is 200 (which means "OK/Success").
        assertEquals(200, response.statusCode(), "Health endpoint should return HTTP 200");
        // Assert that the actual body of the response matches the exact string "OK"
        assertEquals("OK", response.body(), "Health endpoint should return 'OK'");
    }

    @Test
    public void testHubsEndpoint() throws Exception {
        // Build an HTTP GET request aimed at our local health check URL
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:7050/hubs"))
                .GET()
                .build();
        // Send the request and store the response
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        // Verify the server successfully processed the request (HTTP 200)
        assertEquals(200, response.statusCode(), "Hubs endpoint should return HTTP 200");
        // Verify that the server explicitly told our client that the data is CSV format.
        assertEquals("text/csv", response.headers().firstValue("Content-Type").orElse(""), "Content type must be text/csv");
        // Extract the massive CSV string generated by the server
        String body = response.body();
        // Assert that the very top of the CSV body contains the exact standardized headers 
        // We use assertTrue instead of assertEquals because we just want to verify the headers are present, 
        assertTrue(body.contains("hub_id,province,sorting_center,active"), "Response must contain standardized CSV headers");
    }
}
